#include "ngpc.h"

// NOTE_TABLE and BGM_* are generated by midi_to_ngpc.py
extern const unsigned char NOTE_TABLE[]; // pairs: b1,b2
extern const unsigned char BGM_MONO[];    // note_idx, duration pairs
extern const unsigned char BGM_MONO_ATTN[]; // attn, duration pairs (optional)

#define BGM_OP_SET_ATTN  0xF0
#define BGM_OP_SET_ENV   0xF1
#define BGM_OP_SET_VIB   0xF2
#define BGM_OP_SET_SWEEP 0xF3
#define BGM_OP_SET_INST  0xF4

#define Z80_RAM_BASE 0x7000
#define SND_COUNT   (*(volatile u8 *)(Z80_RAM_BASE + 0x0003))
#define SND_BUF     ((volatile u8 *)(Z80_RAM_BASE + 0x0004))

static void WaitBufferFree(void)
{
    u16 timeout = 4000;
    while (SND_COUNT && timeout) {
        timeout--;
    }
}

static void BufferPush(u8 b1, u8 b2, u8 b3)
{
    SND_BUF[0] = b1;
    SND_BUF[1] = b2;
    SND_BUF[2] = b3;
    SND_COUNT = 1;
}

static void PlayNoteIdx(u8 note_idx, u8 attn)
{
    u8 b1 = NOTE_TABLE[note_idx * 2 + 0];
    u8 b2 = NOTE_TABLE[note_idx * 2 + 1];
    u8 b3 = (u8)(0x90 | (attn & 0x0F));

    WaitBufferFree();
    BufferPush(b1, b2, b3);
}

void BGM_PlayMono(const u8 *stream, u8 attn)
{
    u16 i = 0;
    while (1) {
        u8 note = stream[i++];
        u8 dur = 0;
        if (note == 0x00) {
            break;
        }
        if (note == 0xFF) {
            dur = stream[i++];
            // rest
        } else if (note >= BGM_OP_SET_ATTN) {
            // FX opcode (skip payload)
            switch (note) {
            case BGM_OP_SET_ATTN:  i += 1; break;
            case BGM_OP_SET_ENV:   i += 2; break;
            case BGM_OP_SET_VIB:   i += 3; break;
            case BGM_OP_SET_SWEEP: i += 4; break;
            case BGM_OP_SET_INST:  i += 1; break;
            default:               i += 1; break;
            }
            continue;
        } else {
            dur = stream[i++];
            PlayNoteIdx(note, attn);
        }

        // TODO: replace with your tick wait (VBlank counter, timer, etc.)
        while (dur--) {
            // wait 1 tick
        }
    }
}

void BGM_PlayMono_WithAttn(const u8 *notes, const u8 *attn_stream)
{
    u16 i = 0;
    u16 j = 0;
    while (1) {
        u8 note = notes[i++];
        u8 dur = 0;
        if (note == 0x00) {
            break;
        }
        if (note == 0xFF) {
            dur = notes[i++];
            // rest
        } else if (note >= BGM_OP_SET_ATTN) {
            // FX opcode (skip payload)
            switch (note) {
            case BGM_OP_SET_ATTN:  i += 1; break;
            case BGM_OP_SET_ENV:   i += 2; break;
            case BGM_OP_SET_VIB:   i += 3; break;
            case BGM_OP_SET_SWEEP: i += 4; break;
            case BGM_OP_SET_INST:  i += 1; break;
            default:               i += 1; break;
            }
            continue;
        } else {
            dur = notes[i++];
            u8 attn = 0x02;
            if (attn_stream) {
                if (attn_stream[j] == 0xFF) {
                    attn = 0x02;
                } else {
                    attn = attn_stream[j];
                }
                j += 2; // skip (attn, duration)
            }
            PlayNoteIdx(note, attn);
        }

        while (dur--) {
            // wait 1 tick
        }
    }
}

